title: Samsul M
description: >
  Halaman ini didedikasikan untuk istri dan anak-anakku
author:
  name: semarngaji
  email: semarngaji@gmail.com
remote_theme: jekyll/minima@latest
minima:
  skin: dark
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
date_format: "%d-%m-%Y"
