title: @semarngaji
description: >
  Didedikasikan untuk istri dan anak-anakku
theme: minima
minima:
  skin: dark
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
date_format: "%d-%m-%Y"
